# Generated by Django 6.0.5 on 2026-07-27 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_alter_invitation_role_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=32)),
                ('kill_switch', models.BooleanField(default=False, help_text='When True, generation stops immediately for this agent.')),
                ('shadow_mode', models.BooleanField(default=True, help_text='Generate and score drafts but do not deliver. Default on per spec.')),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('current_instructions', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'status'], name='agents_agen_team_id_7848a1_idx')],
            },
        ),
    ]
