# Generated by Django 6.0.5 on 2026-07-27 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('teams', '0004_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=64)),
                ('subject', models.CharField(blank=True, default='', max_length=512)),
                ('channel', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('created_at_external', models.DateTimeField(blank=True, null=True)),
                ('closed_at_external', models.DateTimeField(blank=True, null=True)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_external_id', models.CharField(blank=True, default='', max_length=64)),
                ('qualification', models.CharField(choices=[('SUPPORT', 'Support'), ('SPAM_PHISHING', 'Spam / phishing'), ('MARKETING_INBOUND', 'Marketing inbound'), ('SYSTEM_NOTIFICATION', 'System notification'), ('SOCIAL_NOTIFICATION', 'Social notification'), ('VENDOR_PITCH', 'Vendor pitch'), ('INTERNAL', 'Internal'), ('UNCLEAR', 'Unclear')], default='UNCLEAR', max_length=32)),
                ('qualification_confidence', models.FloatField(blank=True, null=True)),
                ('qualifier_version', models.CharField(blank=True, default='', max_length=64)),
                ('intent', models.CharField(blank=True, default='', max_length=128)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('sentiment', models.CharField(blank=True, default='', max_length=32)),
                ('csat_score', models.FloatField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='integrations.connection')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(db_index=True, max_length=64)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound'), ('INTERNAL_NOTE', 'Internal note')], max_length=32)),
                ('author_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('AGENT', 'Agent'), ('SYSTEM', 'System'), ('BOT', 'Bot')], max_length=32)),
                ('author_external_id', models.CharField(blank=True, default='', max_length=64)),
                ('author_name', models.CharField(blank=True, default='', max_length=255)),
                ('raw_body_html', models.TextField(blank=True, default='')),
                ('raw_body_text', models.TextField(blank=True, default='')),
                ('normalised_text', models.TextField(blank=True, default='')),
                ('is_autoresponder', models.BooleanField(default=False)),
                ('is_resolving_reply', models.BooleanField(default=False)),
                ('classifier_version', models.CharField(blank=True, default='', max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket')),
            ],
            options={
                'ordering': ['sequence', 'sent_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BackfillCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cursor', models.CharField(blank=True, default='', max_length=512)),
                ('tickets_imported', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='RUNNING', max_length=32)),
                ('last_error', models.TextField(blank=True, default='')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfill_checkpoints', to='integrations.connection')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'unique_together': {('team', 'connection')},
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team', 'external_id'], name='tickets_tic_team_id_3c55e8_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team', 'created_at'], name='tickets_tic_team_id_73a85a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['team', 'qualification'], name='tickets_tic_team_id_1733c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('team', 'external_id')},
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['team', 'ticket'], name='tickets_tic_team_id_e35c75_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketmessage',
            unique_together={('team', 'external_id')},
        ),
    ]
