# Generated by Django 6.0.5 on 2026-08-01 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_invitation_role_alter_membership_role'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationGoldLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('SUPPORT', 'Support'), ('SPAM_PHISHING', 'Spam / phishing'), ('MARKETING_INBOUND', 'Marketing inbound'), ('SYSTEM_NOTIFICATION', 'System notification'), ('SOCIAL_NOTIFICATION', 'Social notification'), ('VENDOR_PITCH', 'Vendor pitch'), ('INTERNAL', 'Internal'), ('UNCLEAR', 'Unclear')], max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('labeled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_labels', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold_label', to='tickets.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
