# Generated by Django 6.0.5 on 2026-08-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_m1_sources_and_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='backfillcheckpoint',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backfillcheckpoint',
            name='pages_scanned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='backfillcheckpoint',
            name='phase',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('TICKETS', 'Importing tickets'), ('SOURCES', 'Syncing knowledge sources'), ('DONE', 'Done')], default='QUEUED', max_length=16),
        ),
        migrations.AddField(
            model_name='backfillcheckpoint',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
