# Generated by Django 6.0.5 on 2026-08-01 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
        ('teams', '0004_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('HELP_CENTER_ARTICLE', 'Help Center article'), ('MACRO', 'Macro'), ('TICKET', 'Ticket'), ('WEB_PAGE', 'Web page'), ('FILE', 'File'), ('CURATED_QA', 'Curated Q&A')], max_length=32)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('url', models.URLField(blank=True, default='')),
                ('raw_content', models.TextField(blank=True, default='')),
                ('normalised_content', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='integrations.connection')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'source_type'], name='knowledge_s_team_id_117b77_idx'), models.Index(fields=['team', 'is_active'], name='knowledge_s_team_id_14c415_idx')],
                'unique_together': {('team', 'source_type', 'external_id')},
            },
        ),
    ]
