# Generated by Django 6.0.5 on 2026-08-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_m1_sources_and_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCrawlerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apify_api_key_encrypted', models.BinaryField(blank=True, default=b'')),
                ('apify_actor', models.CharField(blank=True, default='', help_text='Apify actor id, e.g. org~draftline-web-crawler (leave blank until custom actor ships).', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('default_max_depth', models.PositiveIntegerField(default=2)),
                ('default_max_pages', models.PositiveIntegerField(default=30)),
                ('hard_max_pages', models.PositiveIntegerField(default=100)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Platform crawler settings',
                'verbose_name_plural': 'Platform crawler settings',
            },
        ),
    ]
