# Generated by Django 6.0.5 on 2026-08-01 17:00

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_platform_crawler_and_settings'),
        ('teams', '0004_alter_invitation_role_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('char_offset_start', models.PositiveIntegerField(default=0)),
                ('char_offset_end', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('embedder_version', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.source')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['source_id', 'ordinal'],
                'indexes': [models.Index(fields=['team', 'source'], name='knowledge_c_team_id_ca4977_idx')],
                'unique_together': {('team', 'source', 'ordinal')},
            },
        ),
        migrations.CreateModel(
            name='CuratedKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('intent', models.CharField(blank=True, default='', max_length=128)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('RETIRED', 'Retired')], default='DRAFT', max_length=16)),
                ('created_from_delta', models.CharField(blank=True, default='', max_length=64)),
                ('source_ticket_ids', models.JSONField(blank=True, default=list)),
                ('is_deidentified', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedder_version', models.CharField(blank=True, default='', max_length=64)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_curated_knowledge', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'status'], name='knowledge_c_team_id_b0de7e_idx'), models.Index(fields=['team', 'intent'], name='knowledge_c_team_id_32d621_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResolutionPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_ticket_ids', models.JSONField(blank=True, default=list)),
                ('question_text', models.TextField()),
                ('context_summary', models.TextField(blank=True, default='')),
                ('resolution_text', models.TextField()),
                ('intent', models.CharField(blank=True, default='', max_length=128)),
                ('language', models.CharField(blank=True, default='', max_length=16)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('is_exemplar', models.BooleanField(default=False)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('embedder_version', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_pairs', to='knowledge.source')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'indexes': [models.Index(fields=['team', 'intent'], name='knowledge_r_team_id_53fd94_idx'), models.Index(fields=['team', 'is_exemplar'], name='knowledge_r_team_id_b411cc_idx')],
            },
        ),
    ]
