# Generated by Django 6.0.5 on 2026-08-01 20:13

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_m2_chunk_resolution_curated'),
        ('teams', '0004_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='knowledge_chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='resolutionpair',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='knowledge_rp_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
