# Generated by Django 6.0.5 on 2026-08-01 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_m2_hnsw_indexes'),
        ('teams', '0004_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=128)),
                ('label', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, default='seed', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.intentnode')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['slug'],
                'indexes': [models.Index(fields=['team', 'is_active'], name='knowledge_i_team_id_da09d1_idx'), models.Index(fields=['team', 'parent'], name='knowledge_i_team_id_fdea5b_idx')],
                'unique_together': {('team', 'slug')},
            },
        ),
    ]
