cli:
  app_directory: apps
  base_model: apps.teams.models.BaseTeamModel
  css_framework: tailwind
  module_path: apps
  template_directory: templates
  use_teams: true
default_context:
  _pegasus_version: '2026.7'
  api_framework: drf
  author_name: Muhasin R
  bundler: vite
  ci: github_actions
  css_framework: tailwind
  database: postgres
  deploy_platform: google_cloud_run
  description: Application to build SaaS platforms
  docker_mode: services
  docker_setup: default
  domain_name: localhost:8000
  email: muhasin@gauger.in
  enable_github_login: y
  enable_google_login: y
  enable_twitter_login: y
  front_end_framework: htmx
  github_username: muhasin23
  include_static_files: n
  marketing_email_platform: none
  plugins:
  - chat
  post_process: y
  project_name: Draftline
  project_slug: draftline
  python_package_manager: uv
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: in_app
  type_checker: none
  use_2fa: y
  use_admin_docs: n
  use_ai_rules_agents: y
  use_ai_rules_claude: y
  use_ai_rules_cursor: y
  use_ai_rules_junie: n
  use_api_auth: y
  use_api_keys: y
  use_async: y
  use_auto_reload: y
  use_celery: y
  use_cloud_media_storage: y
  use_dark_mode: y
  use_debug_toolbar: n
  use_ecommerce_example: n
  use_examples: y
  use_flowbite: n
  use_health_checks: y
  use_impersonation: y
  use_pegasus_css_classes: n
  use_sentry: y
  use_shadcn: n
  use_subscriptions: y
  use_teams: y
  use_teams_example: n
  use_translations: y
  use_wagtail: n
  use_watchfiles: n
  use_worktrees: n
