# Generated by Django 6.0 on 2026-02-06 08:26

from django.db import migrations


def populate_agent_type(apps, schema_editor):
    """Set agent_type='chat' for all chats that have chat_type='chat' and no agent_type."""
    Chat = apps.get_model("chat", "Chat")
    Chat.objects.filter(agent_type="").update(agent_type="chat")


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chat_agent_type_chat_chat_type"),
    ]

    operations = [
        migrations.RunPython(populate_agent_type, migrations.RunPython.noop),
    ]
