# Generated by Django 6.0 on 2026-02-06 08:27

import apps.ai.types
import apps.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_populate_agent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_type',
        ),
        migrations.AlterField(
            model_name='chat',
            name='agent_type',
            field=models.CharField(choices=apps.chat.models.get_agent_type_choices, default=apps.ai.types.AgentTypes['CHAT'], max_length=30),
        ),
    ]
