# Generated by Django 5.1.1 on 2024-10-15 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
        ("waffle", "__latest__"),
    ]

    operations = [
        # See https://github.com/django-waffle/django-waffle/issues/317#issuecomment-488398832
        migrations.RunSQL(
            "DROP TABLE IF EXISTS waffle_flag_groups"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS waffle_flag_users"
        )
    ]
