# Generated by Django 6.0.5 on 2026-07-27 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('teams', '0004_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('GORGIAS', 'Gorgias'), ('BIGCOMMERCE', 'BigCommerce'), ('GLOBAL_E', 'Global-E'), ('WEBSITE', 'Website'), ('FILES', 'Files')], max_length=32)),
                ('credentials_encrypted', models.BinaryField(blank=True, default=b'')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('ERROR', 'Error'), ('DISCONNECTED', 'Disconnected')], default='PENDING', max_length=32)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('health', models.JSONField(blank=True, default=dict)),
                ('display_name', models.CharField(blank=True, default='', max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='AgentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_connections', to='agents.agent')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_links', to='integrations.connection')),
            ],
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['team', 'provider'], name='integration_team_id_19b48e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('team', 'provider', 'display_name')},
        ),
        migrations.AlterUniqueTogether(
            name='agentconnection',
            unique_together={('agent', 'connection')},
        ),
    ]
