/* tslint:disable */
/* eslint-disable */
/**
 * Draftline
 * Application to build SaaS platforms
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionItem } from './SubscriptionItem';
import {
    SubscriptionItemFromJSON,
    SubscriptionItemFromJSONTyped,
    SubscriptionItemToJSON,
    SubscriptionItemToJSONTyped,
} from './SubscriptionItem';

/**
 * A serializer for Subscriptions which uses the SubscriptionWrapper object under the hood
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    displayName: string;
    /**
     * 
     * @type {Date}
     * @memberof Subscription
     */
    readonly startDate: Date;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    billingInterval: string;
    /**
     * 
     * @type {Date}
     * @memberof Subscription
     */
    readonly currentPeriodStart: Date;
    /**
     * 
     * @type {Date}
     * @memberof Subscription
     */
    readonly currentPeriodEnd: Date;
    /**
     * 
     * @type {boolean}
     * @memberof Subscription
     */
    readonly cancelAtPeriodEnd: boolean;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    readonly status: string;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    readonly quantity: number;
    /**
     * 
     * @type {Array<SubscriptionItem>}
     * @memberof Subscription
     */
    items: Array<SubscriptionItem>;
}

/**
 * Check if a given object implements the Subscription interface.
 */
export function instanceOfSubscription(value: object): value is Subscription {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('startDate' in value) || value['startDate'] === undefined) return false;
    if (!('billingInterval' in value) || value['billingInterval'] === undefined) return false;
    if (!('currentPeriodStart' in value) || value['currentPeriodStart'] === undefined) return false;
    if (!('currentPeriodEnd' in value) || value['currentPeriodEnd'] === undefined) return false;
    if (!('cancelAtPeriodEnd' in value) || value['cancelAtPeriodEnd'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function SubscriptionFromJSON(json: any): Subscription {
    return SubscriptionFromJSONTyped(json, false);
}

export function SubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subscription {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'displayName': json['display_name'],
        'startDate': (new Date(json['start_date'])),
        'billingInterval': json['billing_interval'],
        'currentPeriodStart': (new Date(json['current_period_start'])),
        'currentPeriodEnd': (new Date(json['current_period_end'])),
        'cancelAtPeriodEnd': json['cancel_at_period_end'],
        'status': json['status'],
        'quantity': json['quantity'],
        'items': ((json['items'] as Array<any>).map(SubscriptionItemFromJSON)),
    };
}

  export function SubscriptionToJSON(json: any): Subscription {
      return SubscriptionToJSONTyped(json, false);
  }

  export function SubscriptionToJSONTyped(value?: Omit<Subscription, 'start_date'|'current_period_start'|'current_period_end'|'cancel_at_period_end'|'status'|'quantity'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'display_name': value['displayName'],
        'billing_interval': value['billingInterval'],
        'items': ((value['items'] as Array<any>).map(SubscriptionItemToJSON)),
    };
}

