# Generated by Django 6.0.5 on 2026-07-27 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_code', models.CharField(choices=[('TRIAL', 'Trial'), ('TEAM', 'Team'), ('BUSINESS', 'Business'), ('CUSTOM', 'Custom'), ('INTERNAL', 'Internal')], default='TRIAL', max_length=32)),
                ('interactions_included', models.PositiveIntegerField(default=100)),
                ('interactions_used', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('overage_packs', models.PositiveIntegerField(default=0)),
                ('hard_cap_behaviour', models.CharField(choices=[('BLOCK', 'Block'), ('WARN', 'Warn only')], default='BLOCK', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('billing_provider', models.CharField(choices=[('MANUAL', 'Manual'), ('STRIPE', 'Stripe'), ('RAZORPAY', 'Razorpay'), ('PADDLE', 'Paddle')], default='MANUAL', max_length=16)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement', to='teams.team')),
            ],
            options={
                'verbose_name': 'Team entitlement',
                'verbose_name_plural': 'Team entitlements',
            },
        ),
    ]
